### PR TITLE
Bump posthtml dep

### PR DESCRIPTION
**Pull request by Qard**
## Proposed Changes

0.9.x is out now, which includes the ability to use custom parsers. It'd be nice to get a bump on that dependency. 😸 
## Types of Changes
- [ ] Bug (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature which changes existing functionality)
## Checklist
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) guide
- [x] Lint and unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes are merged and published in downstream modules
### Reviewers: @michael-ciniawsky, ...

0.9.x is out now.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@Qard  :+1:

@voischev I haven't write access here :), i forgot to update @name(s) in the Pull Request template, merge please

**Comment by voischev** [comment]
fix travis errors

**Comment by voischev** [comment]
@michael-ciniawsky have access now

**Review by michael-ciniawsky — COMMENTED** [review]
👍

**Comment by michael-ciniawsky** [comment]
@voischev fixing travis, code style, README later today,  how is your opinion on adding a file.path && file.name to options to posthtml,  I'm asking because it could then be used by file.path exposed by gulp in gulp-posthtml. This would remove the necessity for gulp-tap.

**Comment by voischev** [comment]
kk

**Pull request merged**
